### ISSUE TITLE
Expected async function to be a function

### ISSUE THREAD

**Issue by sidwood** [hapijs/code#103] opened 2017-07-14 08:28 UTC
I expected the following to pass

```javascript
expect(async function () {}).to.be.a.function()
```

but I get 

```
Error: Expected [AsyncFunction] to be a function but got 'object'
```

I'm using code 4.1.0. 

The `typeof` operator returns 'function' for async functions so this looks like an issue but honestly, I'd be surprised if this was missed wich makes me second guess. Maybe I just need to adjust my expectations.

**Comment by cjihrig** [comment] 2017-07-14 13:23
Fixed in https://github.com/hapijs/code/commit/cf692d07817ef37d51c60e96a7ed23e6bb8a1c4a.

**Closed by cjihrig** 2017-07-14 13:23 UTC
Labels: bug

**Comment by tutukin** [comment] 2017-09-26 15:02
Seems that in node 8.x the issue is reproduced due to changed internals:

```javascript
const af = async function() {};
expect(af).to.be.a.function();
```
Expected [AsyncFunction: af] to be a function but got 'object'
```

```

**Comment by cjihrig** [comment] 2017-09-26 15:10
Try it with Code v5 on Node 8.

**Comment by tutukin** [comment] 2017-09-26 15:34
Ok, now I've got it: lab 14.3.1 uses code 4 internally and does not notice code 5 is installed.
